basePath: /
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Address:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      is_default:
        type: boolean
      main_address:
        type: string
      name:
        type: string
      sub_address:
        type: string
      tel:
        type: string
      updatedAt:
        type: string
      user_id:
        type: string
    type: object
  models.AddressRequest:
    properties:
      is_default:
        type: boolean
      main_address:
        type: string
      name:
        type: string
      sub_address:
        type: string
      tel:
        type: string
    type: object
  models.Admin:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: string
      password:
        type: string
      updatedAt:
        type: string
    type: object
  models.Cart:
    properties:
      cartItems:
        items:
          $ref: '#/definitions/models.CartItem'
        type: array
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      quantity:
        type: integer
      updatedAt:
        type: string
      user_id:
        type: string
    type: object
  models.CartItem:
    properties:
      cart_id:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      quantity:
        type: integer
      sku_id:
        type: string
      updatedAt:
        type: string
    type: object
  models.CreateAdminRequest:
    properties:
      email:
        type: string
      password:
        type: string
      secret_key:
        type: string
    type: object
  models.CreateCartItemRequest:
    properties:
      quantity:
        type: integer
      sku_id:
        type: string
    type: object
  models.CreateProductRequest:
    properties:
      description:
        type: string
      img:
        type: string
      name:
        type: string
      productOptions:
        items:
          properties:
            name:
              type: string
            skus:
              properties:
                price:
                  type: number
                quantity:
                  type: integer
              type: object
          type: object
        type: array
    type: object
  models.CreateUserRequest:
    properties:
      email:
        type: string
      f_name:
        type: string
      l_name:
        type: string
      password:
        type: string
      tel:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.LoginResponse:
    properties:
      token:
        type: string
    type: object
  models.Product:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      id:
        type: string
      img:
        type: string
      name:
        type: string
      productOptions:
        items:
          $ref: '#/definitions/models.ProductOption'
        type: array
      reviews:
        items:
          $ref: '#/definitions/models.Review'
        type: array
      skus:
        items:
          $ref: '#/definitions/models.Sku'
        type: array
      trackings:
        items:
          $ref: '#/definitions/models.Tracking'
        type: array
      updatedAt:
        type: string
    type: object
  models.ProductOption:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      name:
        type: string
      product_id:
        type: string
      sku:
        $ref: '#/definitions/models.Sku'
      updatedAt:
        type: string
    type: object
  models.ResetPasswordRequest:
    properties:
      current_password:
        type: string
      new_password:
        type: string
    type: object
  models.Review:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      id:
        type: string
      product_id:
        type: string
      score:
        type: integer
      updatedAt:
        type: string
      user_id:
        type: string
    type: object
  models.Sku:
    properties:
      cartItems:
        items:
          $ref: '#/definitions/models.CartItem'
        type: array
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      price:
        type: number
      product_id:
        type: string
      product_option_id:
        type: string
      quantity:
        type: integer
      updatedAt:
        type: string
    type: object
  models.Tracking:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      payment:
        type: string
      product_id:
        type: string
      status:
        type: string
      updatedAt:
        type: string
      user_id:
        type: string
    type: object
  models.UpdateCartItemRequest:
    properties:
      quantity:
        type: integer
    type: object
  models.UpdateInfoRequest:
    properties:
      email:
        type: string
      f_name:
        type: string
      l_name:
        type: string
      tel:
        type: string
    type: object
  models.User:
    properties:
      address:
        items:
          $ref: '#/definitions/models.Address'
        type: array
      cart:
        $ref: '#/definitions/models.Cart'
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      f_name:
        type: string
      id:
        type: string
      l_name:
        type: string
      password:
        type: string
      reviews:
        items:
          $ref: '#/definitions/models.Review'
        type: array
      tel:
        type: string
      trackings:
        items:
          $ref: '#/definitions/models.Tracking'
        type: array
      updatedAt:
        type: string
    type: object
host: localhost:1323/api
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Alpaca Mall
  version: "1.0"
paths:
  /address/create:
    post:
      consumes:
      - application/json
      description: Create address
      parameters:
      - description: Address object
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/models.AddressRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Address'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Address
  /address/default:
    get:
      consumes:
      - application/json
      description: Get default address
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Address'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Address
  /address/remove/{id}:
    delete:
      consumes:
      - application/json
      description: Remove address
      parameters:
      - description: Address ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Address
  /address/update/{id}:
    put:
      consumes:
      - application/json
      description: Create address
      parameters:
      - description: Address ID
        in: path
        name: id
        required: true
        type: string
      - description: Address object
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/models.AddressRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Address'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Address
  /admin/create:
    post:
      consumes:
      - application/json
      description: Create admin
      parameters:
      - description: Admin object
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/models.CreateAdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Admin'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      tags:
      - Admin
  /auth/admin-login:
    post:
      consumes:
      - application/json
      description: Login admin
      parameters:
      - description: Token
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Token
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      tags:
      - Auth
  /cart:
    get:
      consumes:
      - application/json
      description: Get user Cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Cart'
            type: array
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Cart
  /cart/add:
    post:
      consumes:
      - application/json
      description: Add Cart Item
      parameters:
      - description: Cart Item object
        in: body
        name: cartItem
        required: true
        schema:
          $ref: '#/definitions/models.CreateCartItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CartItem'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Cart
  /cart/remove/{cartItemId}:
    delete:
      consumes:
      - application/json
      description: Remove Cart Item
      parameters:
      - description: cart item id
        in: path
        name: cartItemId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Cart
  /cart/set/{cartItemId}:
    put:
      consumes:
      - application/json
      description: Set Cart Item
      parameters:
      - description: cart item id
        in: path
        name: cartitemid
        required: true
        type: string
      - description: cart item object
        in: body
        name: cartitem
        required: true
        schema:
          $ref: '#/definitions/models.UpdateCartItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CartItem'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Cart
  /product/{id}:
    get:
      consumes:
      - application/json
      description: Get Product By ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      tags:
      - Product
  /product/create:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: Product object
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - Product
  /product/find:
    get:
      consumes:
      - application/json
      description: Get Product by Search
      parameters:
      - description: Search term
        in: query
        name: search
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      tags:
      - Product
  /product/index:
    get:
      consumes:
      - application/json
      description: Get All Product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      tags:
      - Product
  /user/create:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      tags:
      - User
  /user/info:
    get:
      consumes:
      - application/json
      description: Get user by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - User
  /user/reset-password:
    put:
      consumes:
      - application/json
      description: Reset password
      parameters:
      - description: Reset Password object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - User
  /user/update-info:
    put:
      consumes:
      - application/json
      description: Update user info
      parameters:
      - description: Update info object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UpdateInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      security:
      - BearerAuth: []
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
